services:
  backend:
    build: ./ECommerceAPI
    container_name: ecommerce-backend
    networks:
      - ecommerce-network
    expose:
      - "5000"   

  frontend:
    build: .
    container_name: ecommerce-frontend
    networks:
      - ecommerce-network
    expose:
      - "80"    

  caddy:
    image: caddy:2
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - ecommerce-network
    ports:
      - "80:80"
      - "443:443"

networks:
  ecommerce-network:
    driver: bridge
