services:
  backend:
    build: ./ECommerceAPI     
    container_name: ecommerce-backend
    ports:
      - "5000:5000"

  frontend:
    build: .              
    container_name: ecommerce-frontend
    ports:
      - "80:4200"
